### PR TITLE
bosh-lite ops file

### PR DESCRIPTION
**Pull request by vchrisb**
Adding a bosh cli v2 ops file to be used with bosh-lite

### CODE REVIEW

**Comment by vchrisb** [comment]
I'm now part of the emcpcf team and covered under the enterprise cla. Please close and reopen the pull request.

**Comment by rosenhouse** [comment]
@vchrisb You need to publicize your membership in one of the allowed Github Orgs, see the instructions from the bot.

**Comment by vchrisb** [comment]
Thx @rosenhouse, it is now public.

**Comment by Amit-PivotalLabs** [comment]
This PR has a couple things:

1. It removes the explicit `nats` properties under `route_registrar` since that job consumes them as a link.  This change is good in its own right, and should be reflected in any other ops files designed to add c2c networking to another deployment.
2. It switches c2c networking from using mysql to using postgres.  It actually has nothing to do with bosh-lite, aside from the fact that the current ops file in cf-deployment for deployment to bosh-lite also happens to switch from mysql to postgres.

The nats properties removal should probably move into whatever ops file is going to be the common denominator for anyone adding c2c, and then this repo should provide an additional ops file to switch c2c from using mysql to postgres.

cf-deployment should have its own standalone ops file for switching databases too.

**Comment by chinangela** [comment]
Thanks @vchrisb. We actually prefer to use our existing ops-file for bosh-lite (creating a separate postgres ops-file to make it compatible), so we will likely remove that addition. The documentation is great. Let me know if you have any questions.

**Comment by vchrisb** [comment]
@chinangela thank you!

**Pull request merged**
